### ISSUE TITLE
dts 配置过于冗余，控制台打印是否可选

### ISSUE THREAD

**Issue by zhe-qi** [uni-ku/bundle-optimizer#3]
dts 配置 可以精简成

```ts
dts?: {
    asyncImport?: string | false
    asyncComponent?: string | false
  }
```

吗，然后移除控制台相关提示或可选

**Comment by Vanisper** [comment]
配置看得有点冗余，不过我觉得目前到这个颗粒度还可以接受，既支持全局的一些配置又可以详细配置输出路径base还是输出文件名称name，其实都是可选的，需要改base路径直接修改外层的base字段就好了。
不过我确实在写说明文档想说明清楚各参数的时候有点头大😰。
控制台log输出确实可以处理一下，我今天更新一下。

**Comment by Vanisper** [comment]
已更新 : )
